---
title: "Queller-Phil-ADA-homework-1"
author: "Phil Queller"
date: "2/4/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(stringr)
```

# CHALLENGE 1

```{r}

quote <- gsub("[[:punct:]]","","There is grandeur in this view of life, with its several powers, having been originally breathed by the Creator into a few forms or into one; and that, whilst this planet has gone circling on according to the fixed law of gravity, from so simple a beginning endless forms most beautiful and most wonderful have been, and are being evolved")

quote





split_quote <- str_split(quote, " ")[[1]]
split_quote

every_fourth <- split_quote[seq(from = 4, to = 60, by = 4)]
every_fourth

split_quote <- sort(every_fourth, decreasing = TRUE)
split_quote


```
# CHALLENGE 2:

```{r}

m1 <- matrix(
  data = seq(from = 1, to = 159, by = 2),
  nrow = 8,
  ncol = 10
)
m1

m1[5,2]
m1[5:7, ]

m3 <- m1[3:6,4:9]
m3
class(m3)
mode(m3)


```

CHALLENGE 3:

```{r}
a <- array(data = 400:1, dim = c(5, 5, 4, 4))
a

a[1, 1, 1, 2]
a[2, 3, 2, ]
a[1:5, 1:5, 3, 3]

```

CHALLENGE 4:
```{r}
#superfamily
Lorisoidea <- c("Lorisidae","Galagidae")
Lemuroidea <- c("Cheirogaleidae", "Lepilemuridae", "Indriidae", "Lemuridae", "Daubentoniidae")
Tarsioidea <- c("Tarsiidae")
Ceboidea <- c("Cebidae", "Atelidae", "Pitheciidae")
Hominoidea <- c("Hylobatidae", "Hominidae")
Cercopithecoidea <- c("Cercopithecidae")

#parvorder
Platyrrhinni <- list("Superfamily: Ceboidea" = Ceboidea)
Catarrhini <- list("Superfamily: Hominoidea" = Hominoidea, "Superfamily: Cercopithecoidea" = Cercopithecoidea)


#infraorder
Lorisiformes <- list("Superfamily: Lorisoidea" = Lorisoidea)
Lemuriformes <- list("Superfamily: Lemuroidea" = Lemuroidea)
Tarsiiformes <- list("Superfamily: Tarsioidea" = Tarsioidea)
Simiiformes <- list("Parvorder: Platyrrhinni" = Platyrrhinni, "Parvorder: Catarrhini" = Catarrhini)

#suborder
Strepsirhini <- list("Infraorder: Lorisiformes" = Lorisiformes, "Infraorder: Lemuriformes" = Lemuriformes)
Haplorhini <- list("Infraorder: Tarsiiformes" = Tarsiiformes, "Infraorder: Simiiformes" = Simiiformes)

#Order
Primates <- list("Suborder: Strepsirhini" = Strepsirhini, "Suborder: Haplorhini" = Haplorhini)

Primates_taxonomy <- list("Order: Primates" = Primates)
Primates_taxonomy

nwm <- Primates_taxonomy[["Order: Primates"]][["Suborder: Haplorhini"]][["Infraorder: Simiiformes"]][["Parvorder: Platyrrhinni"]][["Superfamily: Ceboidea"]]
nwm

class(nwm)
mode(nwm)

Primates_taxonomy$`Order: Primates`$`Suborder: Haplorhini`$`Infraorder: Tarsiiformes`$`Superfamily: Tarsioidea`

test
```
